"""Teacher-forced BC launcher for Tolstaya-style graph-filter baselines.

This is a thin wrapper around the v18 BC trainer with beta fixed to 1.0, so
rollouts are generated by the hand-coded controller while the selected
Tolstaya-style actor learns the controller labels.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from train_bc import main as bc_main


def main() -> None:
    p = argparse.ArgumentParser(
        description="Train Tolstaya-style K-tap graph-filter baselines with teacher-forced BC.",
    )
    p.add_argument("--variant", choices=["edge", "pure"], default="edge",
                   help="edge = edge-aware fair baseline; pure = topology-only ablation.")
    p.add_argument("--config", type=Path, default=REPO.parent / "configs" / "n10_all_shapes.yaml")
    p.add_argument("--out_dir", type=Path, required=True)
    p.add_argument("--device", default="cuda")
    p.add_argument("--n_envs", type=int, default=64)
    p.add_argument("--rollout_steps", type=int, default=300)
    p.add_argument("--chunk_len", type=int, default=20)
    p.add_argument("--epochs", type=int, default=2,
                   help="Training passes over each teacher-forced collection.")
    p.add_argument("--total_collections", type=int, default=200)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--eval_every", type=int, default=10)
    p.add_argument("--eval_envs", type=int, default=64)
    p.add_argument("--eval_T", type=int, default=300)
    p.add_argument("--save_every", type=int, default=50)
    args, rest = p.parse_known_args()

    actor_type = "tolstaya_edge" if args.variant == "edge" else "tolstaya_pure"
    bc_args = [
        "--config", str(args.config),
        "--out_dir", str(args.out_dir),
        "--device", str(args.device),
        "--actor_type", actor_type,
        "--n_envs", str(args.n_envs),
        "--rollout_steps", str(args.rollout_steps),
        "--chunk_len", str(args.chunk_len),
        "--ppo_epochs", str(args.epochs),
        "--total_collections", str(args.total_collections),
        "--lr", str(args.lr),
        "--eval_every", str(args.eval_every),
        "--eval_envs", str(args.eval_envs),
        "--eval_T", str(args.eval_T),
        "--save_every", str(args.save_every),
        "--dagger_warmup", "1",
        "--dagger_min_beta", "1.0",
    ]
    bc_main(bc_args + rest)


if __name__ == "__main__":
    main()
